# -*- coding: utf-8 -*-
"""
One-shot translator: dich CHUOI HIEN THI (UI) cua 2 app sang tieng Anh.
Chi thay the fragment trong string literal; giu nguyen logic, bien, format.
Comment/docstring khong dich (theo yeu cau).
Chay:  python translate_to_en.py
"""
import io

# ----- MESH (dxf_ramconcept_gui_v13.py) : tieng Viet co dau -----
MESH = [
    ("Chưa cài ezdxf.", "ezdxf is not installed."),
    ("Mở CMD và chạy:  pip install ezdxf", "Open CMD and run:  pip install ezdxf"),
    ("[LỖI] Không tìm thấy file DXF:", "[ERROR] DXF file not found:"),
    ("[LỖI] Thiếu ezdxf. Chạy: pip install ezdxf", "[ERROR] ezdxf missing. Run: pip install ezdxf"),
    ("BƯỚC 1 — ĐỌC FILE DXF", "STEP 1 — READ DXF FILE"),
    ("  Layers: Sàn=", "  Layers: Slab="),
    ("Cột=", "Column="),
    ("Vách=", "Wall="),
    ("Lỗ mở=", "Opening="),
    ("[LỖI] Không đọc được DXF:", "[ERROR] Could not read DXF:"),
    ("Sàn tròn Ø", "Circular slab Ø"),
    ("Lỗ tròn Ø", "Circular hole Ø"),
    ("mm → đa giác ", "mm → polygon "),
    (" cạnh ", " edges "),
    ("(cạnh ≈", "(edge ≈"),
    ("  ✓ Sàn:", "  ✓ Slab:"),
    ("Cột:", "Column:"),
    ("Vách:", "Wall:"),
    ("Lỗ mở:", "Opening:"),
    ("Gộp vách song song:", "Merged parallel walls:"),
    (" đoạn tim", " centerline segments"),
    ("Bỏ vách collinear trùng:", "Removed duplicate collinear walls:"),
    ("  Đồng bộ node cạnh chung sàn/lỗ mở (snap ≤50mm)", "  Synced shared edge nodes of slab/opening (snap ≤50mm)"),
    ("BƯỚC 2 — KẾT NỐI RAM CONCEPT API", "STEP 2 — CONNECT RAM CONCEPT API"),
    ("[LỖI] RAM Concept API:", "[ERROR] RAM Concept API:"),
    ("  ✓ API sẵn sàng", "  ✓ API ready"),
    ("BƯỚC 3 — TẠO MODEL", "STEP 3 — CREATE MODEL"),
    ("  Mở template:", "  Open template:"),
    ("  Tạo model mới", "  Create new model"),
    ("  ✓ Kết nối cad_manager thành công", "  ✓ Connected cad_manager successfully"),
    ("  ✓ Dùng: cad_manager.structure_layer", "  ✓ Using: cad_manager.structure_layer"),
    ("structure_layer lỗi:", "structure_layer error:"),
    ("  ✓ Dùng: cad_manager.element_layer", "  ✓ Using: cad_manager.element_layer"),
    ("element_layer lỗi:", "element_layer error:"),
    ("  ✓ Dùng cad_manager trực tiếp (có slab methods)", "  ✓ Using cad_manager directly (has slab methods)"),
    ("[LỖI] Không tìm được layer để tạo phần tử!", "[ERROR] Could not find a layer to create elements!"),
    ("❌ không tìm thấy", "❌ not found"),
    ("→ Tạo ", "→ Create "),
    (" sàn...", " slabs..."),
    (" cột...", " columns..."),
    (" vách...", " walls..."),
    (" lỗ mở...", " openings..."),
    ("  ⚠ Bỏ qua — không tìm thấy method tạo slab", "  ⚠ Skipped — slab creation method not found"),
    ("  ⚠ Bỏ qua — không tìm thấy method tạo column", "  ⚠ Skipped — column creation method not found"),
    ("  ⚠ Bỏ qua — không tìm thấy method tạo wall", "  ⚠ Skipped — wall creation method not found"),
    ("  ⚠ Bỏ qua — không tìm thấy method tạo opening", "  ⚠ Skipped — opening creation method not found"),
    ("  ⚠ Sàn #", "  ⚠ Slab #"),
    (" bỏ qua — hình học suy biến", " skipped — degenerate geometry"),
    (" set property lỗi:", " set property error:"),
    ("  ✓ Sàn #", "  ✓ Slab #"),
    (" đỉnh, ", " vertices, "),
    ("dày ", "thickness "),
    ("  ⚠ Cột #", "  ⚠ Column #"),
    ("  ✓ Cột #", "  ✓ Column #"),
    (" — tròn ⌀", " — round ⌀"),
    ("góc ", "angle "),
    ("  ⚠ Vách #", "  ⚠ Wall #"),
    ("  ✓ Vách #", "  ✓ Wall #"),
    (" — LineSegment2D, dài ", " — LineSegment2D, length "),
    (" — Polygon2D, dài ", " — Polygon2D, length "),
    (" — 2 Point2D, dài ", " — 2 Point2D, length "),
    (" — 4 floats, dài ", " — 4 floats, length "),
    (" — không tạo được, bỏ qua", " — could not create, skipped"),
    ("  ⚠ Lỗ mở #", "  ⚠ Opening #"),
    ("  ✓ Lỗ mở #", "  ✓ Opening #"),
    ("  Đang tạo FEM mesh (max element = ", "  Creating FEM mesh (max element = "),
    ("  ⚠ Không tìm thấy method mesh — bỏ qua", "  ⚠ Mesh method not found — skipped"),
    ("  ✓ Mesh hoàn tất (", "  ✓ Mesh completed ("),
    ("  ⚠ Mesh không thành công:", "  ⚠ Mesh failed:"),
    ("  → Hình học vẫn được tạo. File sẽ được lưu; ", "  → Geometry was still created. The file will be saved; "),
    ("hãy mở trong RAM Concept và chạy mesh thủ công ", "open it in RAM Concept and run mesh manually "),
    ("(thường do lỗ mở/sàn sát mép tạo phần tử suy biến).", "(usually openings/slabs near edges create degenerate elements)."),
    ("  ⚠ Tất cả dạng gọi ", "  ⚠ All call forms of "),
    ("() đều thất bại", "() failed"),
    ("  Đang lưu file:", "  Saving file:"),
    ("  ✓ Lưu: ", "  ✓ Saved: "),
    ("  ⚠ Không lưu được file — kiểm tra lại API", "  ⚠ Could not save file — check the API"),
    ("  ⚠ Không tìm thấy method đóng concept", "  ⚠ Concept close method not found"),
    ("✓ ĐÃ LƯU:", "✓ SAVED:"),
    ("✗ Lưu file thất bại!", "✗ Failed to save file!"),
    ("[LỖI] AttributeError:", "[ERROR] AttributeError:"),
    ("dày=", "thickness="),
    ("cao=", "height="),
    (" layers tìm thấy)", " layers found)"),
    ("  Layers trong DXF  ", "  Layers in DXF  "),
    ("\"Tất cả\"", "\"All files\""),
    ("Chi tiết lỗi:", "Error detail:"),
    # generic [LOI] cuoi cung
    ("[LỖI] ", "[ERROR] "),
]

# ----- AREA LOAD (dxf_to_ramconcept.py) : tieng Viet khong dau -----
AREA = [
    # button / title full strings TRUOC (de khong bi generic nuot)
    ("Ap dung cho vung DA CHON  (Enter)", "Apply to SELECTED region  (Enter)"),
    ("Ap dung cho TAT CA vung", "Apply to ALL regions"),
    ("Xoa gan vung da chon", "Clear selected region assignment"),
    ("B1: click diem moc 1 tren DXF (ESC huy)", "Step 1: click marker 1 on DXF (ESC to cancel)"),
    ("B2: click diem 1 tren vien SAN (do)", "Step 2: click point 1 on SLAB outline (red)"),
    ("B3: click diem moc 2 tren DXF", "Step 3: click marker 2 on DXF"),
    ("B4: click diem 2 tren vien SAN (do)", "Step 4: click point 2 on SLAB outline (red)"),
    ("Can 2 diem (giai scale + offset)", "Align 2 points (solve scale + offset)"),
    ("Can 2 diem (DXF -> san)", "Align 2 points (DXF -> slab)"),
    ("'Can 2 diem'", "'Align 2 points'"),
    ("Doc san + Tu can", "Read slab + Auto-align"),
    ("Mat bang tai (cuon chuot = zoom, chuot phai keo = pan)", "Load plan (scroll = zoom, right-drag = pan)"),
    ("+ Them vung tu duong bao", "+ Add region from boundary"),
    ("Can diem moc (DXF -> san)", "Align by markers (DXF -> slab)"),
    ("* Click vao duong bao... (ESC huy)", "* Click a boundary... (ESC to cancel)"),
    ("Che do chon duong bao: click len 1 duong bao kin de tao vung.", "Boundary pick mode: click a closed boundary to create a region."),
    ("  Khong tim thay duong bao kin gan vi tri click.", "  No closed boundary found near the click."),
    ("   IMPORT AREA LOAD VAO RAM CONCEPT   ", "   IMPORT AREA LOAD INTO RAM CONCEPT   "),
    # header / labels
    ("Mat bang tai Area", "Area Load Plan"),
    ("Click vao vung tren mat bang de gan SDL + LL", "Click a region on the plan to assign SDL + LL"),
    ("Files & Cau hinh", "Files & Configuration"),
    ("File DXF:", "DXF file:"),
    ("Chia cung <= (mm):", "Arc segment <= (mm):"),
    ("Doc DXF: ", "Read DXF: "),
    ("Doc DXF", "Read DXF"),
    ("File CPT:", "CPT file:"),
    ("Doc layer", "Read layers"),
    ("Don vi:", "Unit:"),
    ("Lop SDL  :", "SDL layer:"),
    ("Lop LL   :", "LL layer :"),
    ("Lop SDL:", "SDL layer:"),
    ("Lop LL:", "LL layer:"),
    ("Gan tai cho vung", "Assign load to region"),
    ("(Chua chon vung)", "(No region selected)"),
    ("Ten tai:", "Load name:"),
    ("Chua co du lieu", "No data yet"),
    ("Chon...", "Browse..."),
    # note block
    ("Quy uoc:", "Convention:"),
    ("- Nhap DUNG dau Fz theo quy", "- Enter the CORRECT Fz sign per model"),
    ("  uoc model (vd -0.5 -> -0.5).", "  convention (e.g. -0.5 -> -0.5)."),
    ("- SDL -> lop 'SI Dead Loading'", "- SDL -> layer 'SI Dead Loading'"),
    ("- LL  -> lop 'Live (Reducible)", "- LL  -> layer 'Live (Reducible)"),
    ("- Moi vung tao 2 area load", "- Each region makes 2 area loads"),
    ("  (1 SDL + 1 LL) neu khac 0.", "  (1 SDL + 1 LL) if non-zero."),
    ("Chon nhieu vung:", "Select multiple regions:"),
    ("- Ctrl+click: them/bo 1 vung", "- Ctrl+click: add/remove a region"),
    ("- Shift+keo: quet chon vung", "- Shift+drag: rubber-band select"),
    ("  (theo tam moi o)", "  (by each centroid)"),
    ("Mau: xam = chua gan,", "Color: gray = unassigned,"),
    ("     xanh = da gan,", "     green = assigned,"),
    ("     cam = dang chon.", "     orange = selected."),
    # status counter
    ("Vung area: ", "Area regions: "),
    ("  |  da gan: ", "  |  assigned: "),
    ("  |  chua gan: ", "  |  unassigned: "),
    # RAM/import internal logs
    ("[LOI] Khong load duoc RAM Concept API:", "[ERROR] Could not load RAM Concept API:"),
    ("Dang khoi dong RAM Concept (headless)...", "Starting RAM Concept (headless)..."),
    ("[LOI] Khong khoi dong duoc RAM Concept:", "[ERROR] Could not start RAM Concept:"),
    ("Mo file:", "Open file:"),
    ("Layer tai trong hien co:", "Existing load layers:"),
    ("  [!] Khong tim thay ", "  [!] Not found "),
    ("' -> tao moi.", "' -> creating new."),
    ("Luu file:", "Save file:"),
    ("=== HOAN THANH: ", "=== DONE: "),
    (" area load da import ===", " area loads imported ==="),
    ("Dang doc hinh hoc san (SlabArea) tu CPT...", "Reading slab geometry (SlabArea) from CPT..."),
    ("[!] Khong tim thay SlabArea nao trong model.", "[!] No SlabArea found in model."),
    ("San: ", "Slab: "),
    ("Dang doc danh sach layer tu CPT...", "Reading layer list from CPT..."),
    ("Tim thay ", "Found "),
    # dialogs / messageboxes
    ("Chon DXF", "Select DXF"),
    ("Chon CPT", "Select CPT"),
    ("Loi DXF", "DXF Error"),
    ("Canh bao", "Warning"),
    ("Thong bao", "Notice"),
    ("Xac nhan", "Confirm"),
    ("Hoan thanh", "Done"),
    ("That bai", "Failed"),
    ("Chon file DXF hop le.", "Select a valid DXF file."),
    ("Chon file CPT truoc.", "Select a CPT file first."),
    ("Chon file CPT.", "Select a CPT file."),
    ("Doc file DXF truoc.", "Read the DXF file first."),
    ("[!] Khong tim thay polyline/hatch KIN nao de lam area load.", "[!] No CLOSED polyline/hatch found to use as area load."),
    ("Gia tri SDL/LL khong hop le.", "Invalid SDL/LL value."),
    ("Hay click chon vung truoc ", "Please select a region first "),
    ("(Ctrl+click hoac Shift+keo de chon nhieu).", "(Ctrl+click or Shift+drag to select multiple)."),
    ("Chua gan tai cho vung nao.", "No load assigned to any region."),
    ("Ti le don vi / Offset khong hop le.", "Invalid unit scale / Offset."),
    ("Import thanh cong! File CPT da luu.", "Import successful! CPT file saved."),
    ("Import that bai. Xem log.", "Import failed. See log."),
    ("Bam 'Doc san + Tu can' truoc de co vien san.", "Click 'Read slab + Auto-align' first to get the slab outline."),
    # canvas / align logs
    ("  [!] Chua co vien san. Bam ", "  [!] No slab outline yet. Click "),
    (" truoc.", " first."),
    ("Gio click DUNG diem do tren vien san do.", "Now click the EXACT matching point on the red slab outline."),
    ("S1 (san) = (", "S1 (slab) = ("),
    ("Gio click diem moc THU 2 tren DXF (xa diem 1).", "Now click the 2nd marker on DXF (far from point 1)."),
    ("Click diem tuong ung tren vien san do.", "Click the matching point on the red slab outline."),
    ("Can 2 diem (giai scale + offset). Chon 2 cap diem TUONG UNG, ", "Align 2 points (solve scale + offset). Pick 2 CORRESPONDING point pairs, "),
    ("moi cap = 1 diem tren DXF + dung diem do tren vien san do. ", "each pair = 1 point on DXF + the same point on the red slab outline. "),
    ("Nen chon 2 diem cheo nhau, cang xa cang chinh xac.", "Choose 2 diagonal points; the farther apart, the more accurate."),
    ("  [!] 2 diem DXF qua gan nhau. Chon lai 2 diem xa nhau.", "  [!] The 2 DXF points are too close. Pick 2 points farther apart."),
    ("  [!] 2 plan co the bi XOAY (lech huong ", "  [!] The 2 plans may be ROTATED (orientation off "),
    ("Cong cu nay chi xu ly scale+dich, chua xoay.", "This tool only handles scale+shift, not rotation."),
    ("  Ket qua: scale=", "  Result: scale="),
    ("Vien san do gio se trung vung tai.", "The red slab outline should now match the load regions."),
    ("Quet chon them ", "Rubber-band selected "),
    (" vung (tong ", " regions (total "),
    # apply / assign logs
    ("Ap dung cho ", "Applied to "),
    ("Gan SDL=", "Assign SDL="),
    ("Da gan SDL=", "Assigned SDL="),
    (" cho TAT CA ", " to ALL "),
    (" cho tat ca ", " to all "),
    ("Da xoa gan cho ", "Cleared assignment of "),
    ("ten='", "name='"),
    (" vung?", " regions?"),
    (" vung.", " regions."),
    (" vung (", " regions ("),
    (" vung  ", " regions  "),
    ("Da chon ", "Selected "),
    ("Vung #", "Region #"),
    ("(tu duong bao)", "(from boundary)"),
    ("  Da tao vung #", "  Created region #"),
    (" tu duong bao (", " from boundary ("),
    (" diem).", " points)."),
    ("Xong: ", "Done: "),
    (" vung area | ", " area regions | "),
    ("(chia cung <= ", "(arc segment <= "),
    ("=== BAT DAU IMPORT ===", "=== START IMPORT ==="),
    ("So vung gan: ", "Assigned regions: "),
    ("  Dang import...  ", "  Importing...  "),
    ("Scale tu suy ra: X=", "Auto scale: X="),
    (" -> dung ", " -> using "),
    ("[!] Scale X/Y lech ", "[!] Scale X/Y differs by "),
    ("% — co the loading plan ", "% — the loading plan may "),
    ("khong cung ti le/huong voi san. Kiem tra lai.", "not match slab scale/orientation. Please check."),
    ("Tu can (", "Auto-align ("),
    ("Vien DO = san mesh. Neu chua khit, dung ", "RED outline = slab mesh. If not aligned, use "),
    (" hoac chinh tay Offset X/Y.", " or adjust Offset X/Y manually."),
    ("Goc", "Corner"),
    ("Tam", "Center"),
    ("Fit view", "Fit view"),
    # generic [LOI] / Loi cuoi cung
    ("[LOI] ", "[ERROR] "),
    ("\"Loi\"", "\"Error\""),
]

# ----- LAUNCHER -----
LAUNCH = [
    ("Chon cong cu de mo", "Select a tool to open"),
    ("Dung hinh hoc / mesh model tu DXF", "Build geometry / mesh model from DXF"),
    ("Gan & import tai SDL / LL tu DXF", "Assign & import SDL / LL loads from DXF"),
]


def apply(path, repls):
    with io.open(path, "r", encoding="utf-8") as f:
        text = f.read()
    for old, new in repls:
        text = text.replace(old, new)
    with io.open(path, "w", encoding="utf-8", newline="") as f:
        f.write(text)
    print("translated:", path)


if __name__ == "__main__":
    apply("dxf_ramconcept_gui_v13.py", MESH)
    apply("dxf_to_ramconcept.py", AREA)
    apply("launcher.py", LAUNCH)
    print("DONE")
